ARG LIQUIBASE_VERSION
FROM liquibase/liquibase:${LIQUIBASE_VERSION}

USER root

# change apk repos
# RUN rm /etc/apk/repositories
# RUN --mount=type=secret,id=apk_repository,target=/etc/apk/repositories,required=true 
RUN apk update && apk add --no-cache postgresql-client curl

# Return to liquibase user space
USER liquibase

# copy entrypoints files
COPY --chown=liquibase:liquibase --chmod=700 ./entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
# CMD ["sleep","36000"]